# Generated by Django 4.1.1 on 2022-09-26 08:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 26, 8, 24, 16, 651889, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 26, 8, 24, 16, 651176, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
