# Generated by Django 4.1.1 on 2022-09-26 08:29

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comment_create_date_alter_post_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 26, 8, 29, 28, 459050, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 26, 8, 29, 28, 458477, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
