# Generated by Django 4.1.2 on 2023-10-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(choices=[("Ema", "Ema"), ("David", "David"), ("Fede", "Fede")], max_length=200),
                ),
                ("code", models.CharField(max_length=4)),
                ("answer", models.CharField(max_length=200)),
            ],
        ),
    ]
