# Generated by Django 4.1.2 on 2023-12-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="name",
            field=models.CharField(
                choices=[
                    ("David", "David"),
                    ("Kun", "Kun"),
                    ("Pollo", "Pollo"),
                    ("Pela", "Pela"),
                    ("Pipi", "Pipi"),
                    ("Ulises", "Ulises"),
                ],
                max_length=200,
            ),
        ),
    ]
